Add zsh autocompletion definition
wardenenv/warden pull request #280
Opened 2020-12-29 15:59 UTC by Lunaetic

This PR adds an autocompletion definition script for zsh that uses sed and awk to parse the output of `usage.help`.

It also adds `sync` and `vnc` to the `usage.help` file, and corrects a typo.

2021-01-03 09:21 UTC, sprankhub commented
Thanks for a start on this! This is a very good start. In the end, it would be nice to have more advanced autocompletion for options or commands, which are "nested" like `warden env up` (currently, it would not complete the `up` if I understand correctly).

2021-04-04 09:01 UTC, sprankhub commented
Yes, this is still relevant.

2021-04-13 19:48 UTC, sprankhub commented
@davidalger, mind merging? There is much more work to do, but it should not stop us from merging this IMHO.

2021-07-13 05:34 UTC, sprankhub commented
@davidalger, mind having a look at this?

2021-10-12 06:22 UTC, sprankhub commented
@davidalger, should we just merge it and improve it whenever someone has time?

2021-11-15 19:15 UTC, sprankhub commented
I still think this should be merged :(

2022-06-29 17:32 UTC, celorodovalho commented
I think this is still relevant and should be merged.

2023-03-13 13:21 UTC, navarr requested changes
Following the instructions did not work.  "plugin 'warden' not found"

Ideally, I'd like to do something similar to what Heroku does to install autocomplete scripts:

https://github.com/heroku/homebrew-brew/blob/master/Formula/heroku.rb

2023-07-07 07:31 UTC, ihor-sviziev commented on autocompletion/zsh/warden.plugin.zsh
> +# Copy this file, `warden.plugin.zsh`, to `~/.oh-my-zsh/plugins/custom/warden/`
maybe better to create a symlink? So if the file will update in next releases, it will be automatically updated there as well.

2024-06-13 18:52 UTC, navarr commented
Closing this as I don't foresee additional work occurring in this PR.  Myles, my man, feel free to reopen if you get a hankering to try a second stab at this.

2024-06-13 18:52 UTC, closed without merging

2025-02-17 00:27 UTC, Lunaetic commented
@navarr 👍🏻 I'll take another stab in the coming weeks.

2025-02-18 02:51 UTC, bap14 commented
@Lunaetic Another thing to consider is that you should start with the base zsh config, and then publish alternative installation for packages like oh-my-zsh. If you just source the completion file you have committed from `~/.zshrc` it does work, but as @navarr pointed out, it only does the top-level commands (env, env-init, db, etc.)