#115: linux permissions
wardenenv/warden pull request #706
Opened 2023-09-23 21:15 UTC by toonvd

@navarr this is mainly a kickoff

To cleanly set a gid and uid, this should happen on build time.
Since images are build in advance, this is not possible.
Adding an entrypoint in docker-compose was not clean enough either in my opinion, hence checking in the project for php-fpm and php-debug, fixing the user and restarting the container.

2023-09-26 10:36 UTC, ihor-sviziev commented
Don't you think we'll have some other permission issues?

2023-09-26 12:18 UTC, toonvd commented
@ihor-sviziev as stated, this was a kickoff, if you can point me towards those other permission issues, I can help.

2023-10-06 13:20 UTC, navarr commented
(Leaving a comment to let you know this isn't being ignored, I've got my eyes on it I'm just also incredibly busy and will get to it in course 👍)

2023-11-30 10:53 UTC, ihor-sviziev requested changes
Hi @toonvd,
I just looked on your changes - looks like they should be moved inside the entrypoint script, similar to this:
https://github.com/wardenenv/images/blob/main/php-fpm/context/docker-entrypoint#L10-L12
Also, we should pass the host uid and host gid to the needed containers.
What do you think about it?

2023-11-30 11:21 UTC, toonvd commented
Hi Ihor!

Will do! Closing this one, will reopen one in images soon.
If you know anyone that can help with testing (switch to Mac for my own laptop), please let me know!

2023-11-30 11:21 UTC, closed without merging

2023-11-30 13:05 UTC, ihor-sviziev commented
The only thing I can suggest - run a virtual machine :) 
I actually not sure if it's doable in that entrypoint file, but I think that would be the best choise